// <auto-generated />
using System;
using HandballManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandballManager.Migrations
{
    [DbContext(typeof(HandballDbContext))]
    partial class HandballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("HandballManager.Models.ChampionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChampionRecords");
                });

            modelBuilder.Entity("HandballManager.Models.LeagueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drawn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("LeagueEntries");
                });

            modelBuilder.Entity("HandballManager.Models.MatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRecordId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("HandballManager.Models.MatchPlayerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Saves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRecordId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayerStats");
                });

            modelBuilder.Entity("HandballManager.Models.MatchRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchweekNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MatchRecords");
                });

            modelBuilder.Entity("HandballManager.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewsType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("HandballManager.Models.PendingTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AgreedMonthlyWage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ToTeamId");

                    b.ToTable("PendingTransfers");
                });

            modelBuilder.Entity("HandballManager.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Acceleration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AerialReach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aggression")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anticipation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CareerAssists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareerGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareerMatchesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareerSaves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Communication")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Composure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Concentration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decisions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Determination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dribbling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eccentricity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finishing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Flair")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrowthAccumulatorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Handling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInjured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetiringAtEndOfSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpingReach")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LastPhaseCheckMatchweek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSeasonAssists")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LastSeasonAverageRating")
                        .HasColumnType("REAL");

                    b.Property<int>("LastSeasonGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSeasonMatchesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSeasonSaves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leadership")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongThrows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Marking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyWage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NaturalFitness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffTheBall")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OneOnOnes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Passing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Positioning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressionPhase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Receiving")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecentAttributeChanges")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reflexes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonAssists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonAttributeChangesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonGoals")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SeasonRatingSum")
                        .HasColumnType("REAL");

                    b.Property<int>("SeasonSaves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SevenMeterTaking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShirtNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tackling")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Teamwork")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Technique")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Throwing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TransferredThisSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HandballManager.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ClubBalance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlayerTeam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TransferBudget")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WageBudget")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("HandballManager.Models.TransferOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ForPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OfferAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OfferedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProposedContractYears")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProposedMonthlyWage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForPlayerId");

                    b.HasIndex("FromTeamId");

                    b.ToTable("TransferOffers");
                });

            modelBuilder.Entity("HandballManager.Models.YouthIntakePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntakeYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestedShirtNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("YouthIntakePlayers");
                });

            modelBuilder.Entity("HandballManager.Models.LeagueEntry", b =>
                {
                    b.HasOne("HandballManager.Models.Team", "Team")
                        .WithOne("LeagueEntry")
                        .HasForeignKey("HandballManager.Models.LeagueEntry", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HandballManager.Models.MatchEvent", b =>
                {
                    b.HasOne("HandballManager.Models.MatchRecord", "MatchRecord")
                        .WithMany("MatchEvents")
                        .HasForeignKey("MatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRecord");
                });

            modelBuilder.Entity("HandballManager.Models.MatchPlayerStat", b =>
                {
                    b.HasOne("HandballManager.Models.MatchRecord", "MatchRecord")
                        .WithMany("PlayerStats")
                        .HasForeignKey("MatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballManager.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchRecord");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HandballManager.Models.PendingTransfer", b =>
                {
                    b.HasOne("HandballManager.Models.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballManager.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballManager.Models.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("HandballManager.Models.Player", b =>
                {
                    b.HasOne("HandballManager.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HandballManager.Models.TransferOffer", b =>
                {
                    b.HasOne("HandballManager.Models.Player", "ForPlayer")
                        .WithMany()
                        .HasForeignKey("ForPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandballManager.Models.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForPlayer");

                    b.Navigation("FromTeam");
                });

            modelBuilder.Entity("HandballManager.Models.YouthIntakePlayer", b =>
                {
                    b.HasOne("HandballManager.Models.Team", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("HandballManager.Models.MatchRecord", b =>
                {
                    b.Navigation("MatchEvents");

                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("HandballManager.Models.Team", b =>
                {
                    b.Navigation("LeagueEntry");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
